---
version: 2.1

orbs:
  executor-tools: twdps/executor-tools@1.1.0
  op: twdps/onepassword@1.0.0
  do: twdps/pipeline-events@0.1.0

# ================================================================= global pipeline parameters

parameters:
  context:
    description: circleci context for all jobs
    type: string
    default: twdps-core-labs-team
  shell-options:
    description: shell options for all jobs
    type: string
    default: op run --env-file op.env -- /bin/bash -eo pipefail
  registry:
    description: publish to this registry
    type: string
    default: ghcr.io/thoughtworks-dps

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

# ================================================================= workflows

workflows:
  version: 2
  alpine-image-pipeline:
    jobs:
      - executor-tools/machine-executor-dev-release:
          name: alpine-dev-build
          context: << pipeline.parameters.context >>
          registry: << pipeline.parameters.registry >>
          dockerfile: Dockerfile.alpine
          image: twdps/circleci-executor-builder
          tag: alpine-edge
          docker-cve-scan: true
          snyk-organization: twdps
          cis-docker-image-scan: true
          skip-base-image: true
          bats-test: true
          test-path: test/circleci_executor_builder_alpine.bats
          container-name: circleci-executor-builder-alpine-edge
          after-checkout:
            - op/env:
                env-file: op.env
          filters: *on-push-main

      - executor-tools/publish:
          name: alpine-release
          shell: << pipeline.parameters.shell-options >>
          context: << pipeline.parameters.context >>
          registry: << pipeline.parameters.registry >>
          pull-tag: alpine-edge
          tag-annotation: alpine-
          image: twdps/circleci-executor-builder
          release-tag: alpine-stable
          sign-image: true
          after-publish:
            - run:
                name: setup cosign keys
                command: |
                  op inject -i cosign.key.env -o cosign.key
                  op inject -i cosign.pub.env -o cosign.pub
          filters: *on-tag-main

  slim-image-pipeline:
    jobs:
      - executor-tools/machine-executor-dev-release:
          name: slim-dev-build
          context: << pipeline.parameters.context >>
          registry: << pipeline.parameters.registry >>
          dockerfile: Dockerfile.slim
          image: twdps/circleci-executor-builder
          tag: slim-edge
          docker-cve-scan: true
          severity-threshold: medium
          snyk-organization: twdps
          cis-docker-image-scan: true
          skip-base-image: true
          bats-test: true
          test-path: test/circleci_executor_builder_slim.bats
          container-name: circleci-executor-builder-slim-edge
          after-checkout:
            - op/env:
                env-file: op.env
          filters: *on-push-main

      - executor-tools/publish:
          name: slim-release
          shell: << pipeline.parameters.shell-options >>
          context: << pipeline.parameters.context >>
          registry: << pipeline.parameters.registry >>
          pull-tag: slim-edge
          tag-annotation: slim-
          image: twdps/circleci-executor-builder
          release-tag: slim-stable
          sign-image: true
          after-publish:
            - run:
                name: setup cosign keys
                command: |
                  op inject -i cosign.key.env -o cosign.key
                  op inject -i cosign.pub.env -o cosign.pub
          filters: *on-tag-main

  generate-release-notes:
    jobs:
      - executor-tools/release:
          shell: << pipeline.parameters.shell-options >>
          context: << pipeline.parameters.context >>
          on-tag: true
          filters: *on-tag-main

  # builds nightly from .unpinned Dockerfile in order to test the latest base image and installed packages
  circleci-executor-builder-nightly-build:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - executor-tools/machine-executor-dev-release:
          name: alpine-nightly-build
          context: << pipeline.parameters.context >>
          registry: << pipeline.parameters.registry >>
          dockerfile: Dockerfile.alpine
          image: twdps/circleci-executor-builder
          tag: alpine-nightly
          docker-cve-scan: true
          snyk-organization: twdps
          cis-docker-image-scan: true
          skip-base-image: true
          bats-test: true
          test-path: test/circleci_executor_builder_alpine.bats
          container-name: circleci-executor-builder-alpine-nightly
          after-checkout:
            - op/env:
                env-file: op.env

      - executor-tools/machine-executor-dev-release:
          name: slim-nightly-build
          context: << pipeline.parameters.context >>
          registry: << pipeline.parameters.registry >>
          dockerfile: Dockerfile.slim
          image: twdps/circleci-executor-builder
          tag: slim-nightly
          docker-cve-scan: true
          snyk-organization: twdps
          cis-docker-image-scan: true
          skip-base-image: true
          bats-test: true
          test-path: test/circleci_executor_builder_slim.bats
          container-name: circleci-executor-builder-slim-nightly
          after-checkout:
            - op/env:
                env-file: op.env
